In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/muhammadumer7804/imf-world-economic-dataset/dataset_2026.csv

# **Step 1 — Load Dataset**

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('/kaggle/input/datasets/muhammadumer7804/imf-world-economic-dataset/dataset_2026.csv', low_memory=False)

print("Shape:", df.shape)
df.head()

Shape: (8200, 79)

,DATASET,SERIES_CODE,OBS_MEASURE,COUNTRY,INDICATOR,FREQUENCY,SCALE,UNIT,COUNTRY_UPDATE_DATE,PUBLICATION_DATE,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
0,IMF.RES:WEO(9.0.0),GBR.NGDPD.A,OBS_VALUE,United Kingdom,"Gross domestic product (GDP), Current prices, ...",Annual,Billions,US dollar,9/13/2025,2026-04-14T13:00:00Z,...,3192.851,3422.072,3695.355,4003.022,4264.794,4466.076,4675.048,4898.448,5148.434,5403.155
1,IMF.RES:WEO(9.0.0),GBR.PCPI.A,OBS_VALUE,United Kingdom,"All Items, Consumer price index (CPI), Period ...",Annual,Units,Index,9/13/2025,2026-04-14T13:00:00Z,...,121.665,130.550,133.853,138.368,142.800,146.253,149.178,152.161,155.205,158.309
2,IMF.RES:WEO(9.0.0),ITA.LP.A,OBS_VALUE,Italy,"Population, Persons for countries / Index for ...",Annual,Millions,NaN,9/23/2025,2026-04-14T13:00:00Z,...,59.030,58.997,58.971,58.934,58.879,58.806,58.716,58.611,58.493,58.364
3,IMF.RES:WEO(9.0.0),LIE.LE.A,OBS_VALUE,"Liechtenstein, Principality of","Employed persons, Persons for countries / Inde...",Annual,Millions,NaN,9/29/2025,2026-04-14T13:00:00Z,...,0.043,0.043,0.043,0.044,0.044,0.045,NaN,NaN,NaN,NaN
4,IMF.RES:WEO(9.0.0),GBR.GGXONLB.A,OBS_VALUE,United Kingdom,"Primary net lending (+) / net borrowing (-), G...",Annual,Billions,Domestic currency,9/13/2025,2026-04-14T13:00:00Z,...,-26.845,-101.457,-116.298,-83.997,-38.632,-12.753,8.109,36.219,48.305,50.306

# **Step 2 — Column Names Check**

In [3]:
print(df.columns[:27].tolist())

['DATASET', 'SERIES_CODE', 'OBS_MEASURE', 'COUNTRY', 'INDICATOR', 'FREQUENCY', 'SCALE', 'UNIT', 'COUNTRY_UPDATE_DATE', 'PUBLICATION_DATE', 'UPDATE_DATE', 'METHODOLOGY', 'METHODOLOGY_NOTES', 'LATEST_ACTUAL_ANNUAL_DATA', 'HISTORICAL_DATA_SOURCE', 'BASE_YEAR', 'START_END_MONTHS_OF_REPORTING_YEAR', 'CHAIN_WEIGHTED', 'BASIS_OF_PROJECTIONS', 'VALUATION', 'PRICES_SECTOR_HARMONIZED_PRICES', 'LABOR_SECTOR_EMPLOYMENT_TYPE', 'FISCAL_SECTOR_GENERAL_GOVERNMENT_COMPOSITION', 'FISCAL_SECTOR_VALUATION_OF_DEBT', 'FISCAL_SECTOR_INSTRUMENTS_INCLUDED_IN_GROSS_AND_NET_DEBT', 'TRADE_SECTOR_OIL_COVERAGE', 'PRIMARY_DOMESTIC_CURRENCY']

# **Step 3 — Select Only Useful Columns**

In [4]:
year_columns = [str(year) for year in range(1980, 2032)]
useful_columns = ['COUNTRY', 'INDICATOR', 'UNIT'] + year_columns

df_clean = df[useful_columns].copy()

print(df_clean.shape)
df_clean.head()

(8200, 55)

,COUNTRY,INDICATOR,UNIT,1980,1981,1982,1983,1984,1985,1986,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
0,United Kingdom,"Gross domestic product (GDP), Current prices, ...",US dollar,604.664,589.092,560.122,533.763,505.859,538.269,656.445,...,3192.851,3422.072,3695.355,4003.022,4264.794,4466.076,4675.048,4898.448,5148.434,5403.155
1,United Kingdom,"All Items, Consumer price index (CPI), Period ...",Index,31.268,35.079,38.064,40.043,41.824,43.982,45.577,...,121.665,130.550,133.853,138.368,142.800,146.253,149.178,152.161,155.205,158.309
2,Italy,"Population, Persons for countries / Index for ...",NaN,56.388,56.479,56.524,56.563,56.565,56.588,56.598,...,59.030,58.997,58.971,58.934,58.879,58.806,58.716,58.611,58.493,58.364
3,"Liechtenstein, Principality of","Employed persons, Persons for countries / Inde...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.043,0.043,0.043,0.044,0.044,0.045,NaN,NaN,NaN,NaN
4,United Kingdom,"Primary net lending (+) / net borrowing (-), G...",Domestic currency,-1.735,-5.118,-1.751,-2.646,-1.942,-0.534,0.153,...,-26.845,-101.457,-116.298,-83.997,-38.632,-12.753,8.109,36.219,48.305,50.306

# **Step 4 — Convert Wide Format to Long Format (Melt)**

In [5]:
df_long = df_clean.melt(
    id_vars=['COUNTRY', 'INDICATOR', 'UNIT'],
    value_vars=year_columns,
    var_name='Year',
    value_name='Value'
)

df_long['Year'] = df_long['Year'].astype(int)

print(df_long.shape)
df_long.head(10)

(426400, 5)

,COUNTRY,INDICATOR,UNIT,Year,Value
0,United Kingdom,"Gross domestic product (GDP), Current prices, ...",US dollar,1980,604.664
1,United Kingdom,"All Items, Consumer price index (CPI), Period ...",Index,1980,31.268
2,Italy,"Population, Persons for countries / Index for ...",NaN,1980,56.388
3,"Liechtenstein, Principality of","Employed persons, Persons for countries / Inde...",NaN,1980,NaN
4,United Kingdom,"Primary net lending (+) / net borrowing (-), G...",Domestic currency,1980,-1.735
5,Malta,"Employed persons, Persons for countries / Inde...",NaN,1980,NaN
6,United States,"Revenue, General government, Percent of GDP",Percent,1980,NaN
7,United States,"Gross domestic product (GDP), Price deflator, ...",Index,1980,39.372
8,Latin America and the Caribbean (LAC),"Gross capital formation, Percent of GDP",Percent,1980,23.739
9,Honduras,"Gross domestic product (GDP), Current prices, ...",Domestic currency,1980,2149.934